name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: front:latest

      - name: Remove current dotnetapp service
        run: |
          docker compose -f /home/support/docker-compose.yaml rm -f -s -v nodejsapp

      - name: Run Docker Compose
        run: |
          docker compose -f /home/support/docker-compose.yaml up -d

      - name: Check running containers
        run: |
          docker ps
